CREATE TABLE IF NOT EXISTS "images" (
	id SERIAL PRIMARY KEY NOT NULL,
  url VARCHAR(255),
  s3_key VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "users" (
	id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  image_id INTEGER NOT NULL,
  gender VARCHAR(255) NOT NULL,
  FOREIGN KEY(image_id) REFERENCES "images"("id")
);
